name: flutter_firebase_phone_auth_riverpod
description: Using Riverpod to handle Firebase Phone Authentication
publish_to: 'none'
version: 1.2.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  firebase_auth: ^3.5.1
  firebase_core: ^1.20.0
  flutter:
    sdk: flutter
  flutter_libphonenumber: ^1.2.4
  flutter_riverpod: ^1.0.4
  freezed_annotation: ^2.1.0
  pinput: ^2.2.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  
flutter:
  uses-material-design: true
  assets:
    - assets/
    
